# Generated by Django 5.0.6 on 2024-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_completed_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lesson_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='strike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
