# Generated by Django 5.0.6 on 2024-06-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_last_lesson_completion_date_user_strike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_lesson_completion_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='strike',
        ),
    ]
