# Generated by Django 5.0.6 on 2024-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_last_lesson_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strike',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='strike_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
