# Generated by Django 5.0.6 on 2024-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_strike_user_strike_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
