# Generated by Django 5.0.6 on 2024-06-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_last_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='week_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
