# Generated by Django 5.0.2 on 2024-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(default='default_lesson.avif', upload_to='languages_images'),
        ),
    ]
