# Generated by Django 5.0.2 on 2024-05-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('blank_words', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('var1', models.TextField()),
                ('var2', models.TextField()),
                ('var3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TranslateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('lesson_level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='language.level')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(default='default_lesson.avif', upload_to='lessons')),
                ('fill_in_the_blank_tests', models.ManyToManyField(blank=True, related_name='lessons', to='lesson.fillintheblankquestion')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='language.language')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='language.level')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.lessoncategory')),
                ('tests', models.ManyToManyField(blank=True, related_name='lessons', to='lesson.question')),
                ('translate_tests', models.ManyToManyField(blank=True, related_name='lessons', to='lesson.translatequestion')),
            ],
        ),
    ]
