# Generated by Django 5.0.2 on 2024-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('blank_words', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='listen_tests',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lesson.listenquestion'),
        ),
    ]
