# Generated by Django 5.0 on 2024-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_test_remove_question_test_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tests',
            field=models.ManyToManyField(related_name='lessons', to='lesson.question'),
        ),
    ]
