# Generated by Django 5.0.2 on 2024-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_listenquestion_lesson_listen_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
