# Generated by Django 5.0 on 2024-05-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lesson_test_lesson_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='default_lesson.avif', upload_to='lessons'),
        ),
    ]
