# Generated by Django 5.0.2 on 2024-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('blank_words', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='fill_in_the_blank_tests',
            field=models.ManyToManyField(related_name='lessons', to='lesson.fillintheblankquestion'),
        ),
    ]
