# Generated by Django 5.0.2 on 2024-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_fillintheblankquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fill_in_the_blank_tests',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lesson.fillintheblankquestion'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lesson.question'),
        ),
    ]
